# Generated by Django 6.0.1 on 2026-01-28 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='sections/covers/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок отображения (меньше - выше')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True, help_text='Короткое описание для списков')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='posts/covers/')),
                ('status', models.CharField(choices=[('draft', 'черновик'), ('Published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Закрепить в разделе/на главной')),
                ('order', models.PositiveIntegerField(default=0, help_text='Порядок внутри раздела')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_authored', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='content.section')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='content.tag')),
            ],
            options={
                'ordering': ['order', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/images/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.post')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PostRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, help_text='Короткая заметка: что изменилось', max_length=200)),
                ('is_published_snapshot', models.BooleanField(default=False, help_text='Снимок в момент публикации')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post_revisions', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.post')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['post', '-created_at'], name='content_pos_post_id_bb296d_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='content_pos_status_90c640_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['section', 'status'], name='content_pos_section_152c5b_idx'),
        ),
    ]
