# Generated by Django 6.0.1 on 2026-01-28 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='current_revision',
            field=models.ForeignKey(blank=True, help_text='Ревизия, отображаемая на сайте', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='content.postrevision'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Закрепить в разделе или на главной'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('archived', 'Архив')], default='draft', max_length=20),
        ),
    ]
