# Generated by Django 6.0.1 on 2026-02-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_activity_options_alter_activity_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
