# Generated by Django 6.0.1 on 2026-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_post_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('create', 'Создание'), ('update', 'Обновление'), ('publish', 'Публикация'), ('archive', 'Архив'), ('delete', 'Удаление')], max_length=10),
        ),
    ]
