# Generated by Django 6.0.1 on 2026-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_activity_post_alter_postimage_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='cover_image',
        ),
    ]
