# Generated by Django 6.0.1 on 2026-02-07 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_remove_section_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='catalog',
            field=models.CharField(choices=[('sinyi', 'Синь И Цюань'), ('taiji', 'Тайцзи'), ('classes', 'Занятия')], default='sinyi', max_length=50, verbose_name='Каталог'),
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.section', verbose_name='Родительский раздел'),
        ),
    ]
