# Generated by Django 6.0.1 on 2026-02-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_catalog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
