# Generated by Django 6.0.1 on 2026-02-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_new_posts',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о новых публикациях'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_updates',
            field=models.BooleanField(default=True, verbose_name='Уведомлять об обновлениях статей'),
        ),
    ]
