# Generated by Django 6.0.1 on 2026-02-09 19:12

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_userprofile_email_alter_userprofile_notify_new_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_token_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
