# Generated by Django 6.0.1 on 2026-02-10 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_userprofile_email_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_token',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email_token_created',
        ),
    ]
